version: "3.5"

x-common:
  &x-common
  env_file:
    - ".env"

  logging:
    options:
      max-file: "5"
      max-size: 10m

  tty: true
  stdin_open: true

x-bot-service:
  &x-bot-service
  <<: *x-common

  image: r/place-bot
  build:
    context: .

  command: node bot.js

services:
  bot:
    <<: *x-bot-service

# Add more instances with more env files if you have multiple accounts
#  bot2:
#    <<: *x-bot-service
#    env_file:
#      - ".env2"
